/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nuckrieg.degredon.panels;

import com.nuckrieg.degredon.specifics.Player;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Nuckrieg
 */
public class HealthBar extends javax.swing.JPanel {

    private Player player;
    private final Player playerToIgnore;

    /**
     * Creates new form HealthBar
     *
     * @param player
     */
    public HealthBar(Player player, Player playerToIgnore) {
        this.player = player;
        this.playerToIgnore = playerToIgnore;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Graphics2D g2 = (Graphics2D) g;
//        System.out.println("WTF IS NULL?");
//        System.out.println("G " + g);
//        System.out.println("P " + player);
//        System.out.println("H " + player.getCurrentHp());
//        System.out.println("S " + player.getStats());
        g.setColor(Color.black);
        g.fillRect(0, 0, 400, 50);
        g.setColor(Color.red);
        if (player.getCurrentHp() > 0 && playerToIgnore.getCurrentHp() > 0) {
            g.fillRect(0, 0, (int) (400 * (player.getCurrentHp() / player.getStats().MAX_HP)), 50);
        } else {
            g.fillRect(0, 0, 0, 0);
        }
        

    }

//    public void callForRepaint() {
////        System.out.println("HP IS NOW " + player.getCurrentHp());
//        repaint();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
